import {supabase} from '../../../shared/js/supabase.js';
import {requireUser,signOut,changePassword,getMfaFactors,enrollMfa,verifyMfa} from '../../../shared/js/auth.js';
import {isStrongPassword,PASSWORD_POLICY_MESSAGE} from '../../../shared/js/password-policy.js';
const session=await requireUser(['admin']); if(!session) throw new Error('Unauthorized');
const $=q=>document.querySelector(q);
$('#logout').onclick=e=>{e.preventDefault();signOut()};
async function loadAudit(){const {data,error}=await supabase.from('audit_logs').select('action,entity_type,entity_id,details,created_at').order('created_at',{ascending:false}).limit(300); $('#rows').innerHTML=error?`<tr><td colspan="4">${escapeHtml(error.message)}</td></tr>`:(data||[]).map(x=>`<tr><td>${escapeHtml(new Date(x.created_at).toLocaleString())}</td><td><strong>${escapeHtml(x.action)}</strong></td><td>${escapeHtml(x.entity_type)} ${x.entity_id?`<small>${escapeHtml(x.entity_id)}</small>`:''}</td><td><small>${escapeHtml(JSON.stringify(x.details||{}))}</small></td></tr>`).join('')||'<tr><td colspan="4">No recent activity.</td></tr>'}
async function loadMfa(){const {data,error}=await getMfaFactors();if(error){$('#mfaStatus').textContent=error.message;return}const verified=(data?.totp||[]).filter(x=>x.status==='verified');$('#mfaStatus').className=verified.length?'ok':'notice';$('#mfaStatus').textContent=verified.length?'✓ Authenticator MFA is enabled for this administrator.':'MFA is not enabled. We recommend enabling it for administrator accounts.';$('#startMfa').hidden=!!verified.length}
$('#startMfa').onclick=async()=>{ $('#mfaMsg').textContent=''; const {data,error}=await enrollMfa(); if(error){$('#mfaMsg').textContent=error.message;return} $('#qr').src=data.totp.qr_code; $('#mfaSetup').hidden=false; $('#startMfa').hidden=true; window.mfaFactorId=data.id; };
$('#verifyMfa').onclick=async()=>{const code=$('#mfaCode').value.trim();if(!/^\d{6}$/.test(code)){ $('#mfaMsg').textContent='Enter the 6-digit authenticator code.';return;}const {error}=await verifyMfa(window.mfaFactorId,code);if(error){$('#mfaMsg').textContent=error.message;return;}$('#mfaMsg').textContent='MFA enabled successfully.';$('#mfaSetup').hidden=true;await loadMfa();};
$('#passwordForm').onsubmit=async e=>{e.preventDefault();const a=$('#newPassword').value,b=$('#confirmPassword').value;if(!isStrongPassword(a)){$('#passwordMsg').textContent=PASSWORD_POLICY_MESSAGE;return}if(a!==b){$('#passwordMsg').textContent='Passwords do not match.';return}const {error}=await changePassword(a);$('#passwordMsg').textContent=error?error.message:'Password changed successfully.';if(!error)e.target.reset();};
async function loadAlerts(){const {data,error}=await supabase.from('security_alerts').select('id,created_at,severity,title,details,resolved').eq('resolved',false).order('created_at',{ascending:false}).limit(100);$('#alertRows').innerHTML=error?`<tr><td colspan="5">${escapeHtml(error.message)}</td></tr>`:(data||[]).map(x=>`<tr><td>${escapeHtml(new Date(x.created_at).toLocaleString())}</td><td><strong>${escapeHtml(x.severity)}</strong></td><td>${escapeHtml(x.title)}</td><td><small>${escapeHtml(JSON.stringify(x.details||{}))}</small></td><td><button type="button" class="btn secondary" data-alert="${escapeHtml(x.id)}">Resolve</button></td></tr>`).join('')||'<tr><td colspan="5">No open security alerts.</td></tr>';document.querySelectorAll('[data-alert]').forEach(b=>b.onclick=async()=>{b.disabled=true;const {error}=await supabase.rpc('resolve_security_alert',{p_alert_id:b.dataset.alert,p_note:'Resolved from Security Center'});if(error)$('#msg').textContent='Security alert could not be resolved.';await loadAlerts()})}
$('#reloadAlerts').onclick=loadAlerts;$('#reloadAudit').onclick=loadAudit;
const scanBtn=document.querySelector('#runSecurityScan');
scanBtn?.addEventListener('click',async()=>{scanBtn.disabled=true;const {data,error}=await supabase.rpc('admin_run_security_scan');document.querySelector('#msg').textContent=error?.message||(data?`Security scan complete. ${data.created||0} new alert(s).`:'Security scan complete.');scanBtn.disabled=false;await loadAlerts();});
loadAudit();loadMfa();loadAlerts();

function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
